# Add 'repo' label to any root file changes
root:
- '*'

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['src/**/*.c']

algoritm:
- any: ['algos/**/*.c']
  
libft:
- any: ['libft/**/*.c']
  
operation:
- any: ['operation/**/*.c']
  
include:  
- any: ['inc/*.h']
# label1:
# - example1/*
# label1:
# - any: ['example1/*']
