# Add 'repo' label to any root file changes
root:
- '*'

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['src/**/*.c']

algoritm:
  - 'algos/**/*.c'
  
libft:
  - 'libft/**/*.c'
  
operation:
  - 'operation/**/*.c'
  
include:  
  - 'inc/*.h

# # Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
# frontend:
# - any: ['src/**/*.js']
#   all: ['!src/main.js']
