name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
#    - name: configure
#      run: ./configure
    - name: make
      run: make
    - name: leaks
      run: make debug
    - name: norminette
      run: make norm
